#!/bin/bash

# Orik is a utility for combining multiple tasks to be carried out on the command line.
SCRIPTNAME=orik
VERSION=0.2a

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CURRENT_DIR=$PWD
BASENAME=`basename $0`

cd $SCRIPT_DIR
chmod +x modules/*

MINIMUM_ARGS=1 # Minimum arguments required, otherwise usage() is run.

function usage() {
	echo "Usage: ./$SCRIPTNAME run [options] [module]"
	echo
	echo "Orik can also run multiple modules per run ordered as inputted."
	echo
	echo "General:"
	echo "-l	Lists all $SCRIPTNAME modules."
	echo "-v	Shows $SCRIPTNAME version."
	echo "-i	Installs $SCRIPTNAME globally."
	echo "-u	Uninstalls $SCRIPTNAME."
	return
}

if [ -f config.txt ]
  then
    . config.txt
  else
	echo "Missing configuration file. Aborting."
	exit
fi

if [ "$1" = "-l" ]
  then
    echo "Available Modules: ${MODULES[@]}"    
	exit
fi

if [ "$1" = "-v" ]
  then
	echo "$SCRIPTNAME version $VERSION"
	exit
fi

if [ "$1" = "-i" ]
	then
		echo "Installing Orik globally..."
		
		path=$PATH
		bin=${path%%:*}

		if [ ! -h $bin/$BASENAME ]
			then
				ln -s $CURRENT_DIR/$BASENAME $bin/$BASENAME
				ln -s $CURRENT_DIR/modules $bin/modules
				ln -s $CURRENT_DIR/config.txt $bin/config.txt
		fi
		exit
fi

if [ "$1" = "-u" ]
	then
		echo "Uninstalling Orik..."
		
		path=$PATH
		bin=${path%%:*}
		
		rm $bin/$BASENAME
		rm $bin/config.txt
		rm -rf $bin/modules
		
		exit
fi


if [ $# -lt $MINIMUM_ARGS ]
  then
    usage
fi

if [ "$1" = "run" ]
  then
	if [ "$2" = "all" ]
	  then
	    for i in "${MODULES[@]}"
		  do
			cd $CURRENT_DIR
		    . $SCRIPT_DIR/modules/$i
		  done
	elif [ "$2" ]
	  then
		cd $CURRENT_DIR
		. $SCRIPT_DIR/modules/$2
		exit
	fi
fi